// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:passman/features/home/models/account_model.dart';
import 'package:passman/features/home/models/card_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AccountModelAdapter());
    registerAdapter(CardModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AccountModelAdapter());
    registerAdapter(CardModelAdapter());
  }
}
